[project]
name = "erddap-compliance"
version = "0.2.0"
description = "Run ioos-compliance on all datasets of an ERDDAP server"
readme = "README.md"
requires-python = ">=3.11"
license = "AGPLv3"
dependencies = [
    "compliance-checker>=5.4.2",
    "erddapy>=2.2.4",
]

[dependency-groups]
dev = [
    "ruff>=0.14.5",
]
