name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format
      - name: Run script
        run: |
          # DB-backed dataset
          uv run python -m erddap_compliance https://data.cioospacific.ca/erddap --dataset_id ECCC_MSC_BUOYS

          # file backed dataset
          uv run python -m erddap_compliance https://data.cioospacific.ca/erddap --dataset_id BCSOP_monthly

          # Grid dataset
          uv run python -m erddap_compliance https://erddap.ogsl.ca/erddap --dataset_id mpoAlguesToxiquesPred1-24
